#!/bin/bash

subdirs="ethereum-rlp ethereum-util ethereum-merkle-patricia-db ethereum-encryption ethereum-data-sql hminer ethereum-client-haskell p2p-server hserver-eth"

for i in $subdirs
do
	cd $i
	cabal install --force-reinstalls
	cd ..
done
